### ISSUE TITLE
domain forwarding from macromolecular.science

### ISSUE THREAD

**Issue by nicholas-pearce** [macromolecular/macromolecular.github.io#1]
I would like to have the domain macromolecular.science forward to https://macromolecular.github.io. Currently it works with http://macromolecular.science but this obviously isn't secure and some browsers block it.I guess we need to get a security certificate for it to do this via https? Help!

**Comment by kelly-ly** [comment]
@nicholas-pearce I believe I may need your insights and assistance on this:

## 1. Determining the Type of Certificate We Need**
SSL certificates can be broadly categorized based on:

### Validation Level:

**Domain Validation (DV):** This is the most basic level of verification. It only verifies if the applicant has control over the specified domain name. Verification is typically done by sending an email to the domain name or asking the applicant to create a specific DNS record. DV certificates are issued quickly and are cost-effective. If our primary need is a static website without user interaction or data collection, like [macromolecular.github.io](https://macromolecular.github.io/), this might be sufficient.

**Organization Validation (OV)**: Beyond validating domain ownership, the CA also verifies certain organizational details like name and address. This could be a suitable choice if we aim to make our website appear more trustworthy.

**Extended Validation (EV)**: This is the most rigorous level of validation. Besides domain and organization verification, the CA conducts additional checks, such as verifying the company's legal existence and physical address. It seems unnecessary for our current needs.

### Secured Domains:

**Single Domain**: Protects a single domain name without covering any subdomains. If we don't anticipate using subdomains, this is a straightforward choice.

**Wildcard**: Protects the primary domain and all its subdomains. For instance, a certificate for *.macromolecular.science would cover macromolecular.science, pandda.macromolecular.science, echt.macromolecular.science, and so on. This seems like a viable option.

**Multi-Domain**: Protects multiple distinct domain names. For example, it could cover macromolecular.science and proteinanalysis.bio. Currently, this doesn't seem necessary.

## 2. Selecting a Certificate Authority
If my research is accurate and the domain name is registered with **GoDaddy**, we might consider using GoDaddy as our CA. Generally, the differences between CAs are minimal. Here are GoDaddy’s pricing details for various SSL certificates:
|       | Domain Validation   |                     | Organization Validation |                     |
|-------|:-------------------:|:-------------------:|:-----------------------:|:-------------------:|
|       | Single Domain       | Wildcard            | Single Domain           | Wildcard            |
| 1 year|      $99.99         |    $449.99          | $169.99                 | $429.99             |
| 2 year|      $89.99         |    $372.99          | $149.99                 | $389.99             |
| 3 year|      $69.99         |    $295.99          | $135.99                 | $343.99             |
| 5 year|      $69.99         |    $295.99          | $135.99                 | -                   |

## 3. Generating a Certificate Signing Request (CSR)
From what I understand, the two IP addresses associated with macromolecular.science point to AWS services. However, I'm uncertain if we're also utilizing AWS cloud servers. We need to generate a CSR on our web server. The generation process is contingent on the web server software in use.

After we decide/solve these issues, we can work on the next step of application work.
